# Plugins:
gems: [jekyll-paginate, jekyll-assets]

# Basic information:
title: Glimpse Framework
url: http://glimpseframework.org

# Social media:
twitter: glimpse_fw

# Blog:
paginate: 10
paginate_path: "/posts/:num/"

# Syntax coloring:
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Examples:
collections:
  examples:
    output: true
    permalink: /examples/:path/

# Versions:
glimpse_version: "0.3"
kotlin_version: "1.0.4"

# Assets:
assets:
  compress:
    css: true
    js: true
  cache_type: filesystem
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "*.css"
  sources:
    - _assets/css
    - _assets/img
    - _assets/js